### ISSUE TITLE
Error when doing animated simulation on blender 3.0

### ISSUE THREAD

**Issue by Sinasta** [rgsouthall/vi-suite061#1]
Hello there. I get this error when doing an light simulation with a static geometry but for more than one day (hour) on Blender 3.0. Vi-suite06 works perfectly fine on blender 3.0 by the way.

Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/vi_operators.py", line 1088, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_calc.py", line 127, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in basiccalcapply
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in <listcomp>
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
KeyError: 'key not in subgroup dict'

location: <unknown location>:-1

After another test i found out that i get the same exact error when trying a simulation with static lightning but animated geometry

**Comment by Sinasta** [comment]
Thanks for the incredible work you are doing. I dont mean to hurry you i just want to report that the error with animations is still persisting on blender 3.0 with python 3.9:

Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/vi_operators.py", line 1092, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_calc.py", line 127, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in basiccalcapply
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in <listcomp>
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
KeyError: 'key not in subgroup dict'

location: <unknown location>:-1
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Warning: Current frame is not within the exported frame range and has been adjusted
Error: Python: Traceback (most recent call last):
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/vi_operators.py", line 1092, in invoke
    calcout = li_calc(self, simnode, livisimacc(simnode))
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_calc.py", line 127, in li_calc
    bccout = ovp.basiccalcapply(scene, frames, rtcmds, simnode, curres, pfile)
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in basiccalcapply
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/livi_func.py", line 538, in <listcomp>
    reslists.append(['All', 'Zone', self.id_data.name, 'Average irradiance (W)', ' '.join(['{:.3f}'.format(self['oave']['virrad{}'.format(frame)]) for frame in frames])])
KeyError: 'key not in subgroup dict'

location: <unknown location>:-1

**Comment by Sinasta** [comment]
This error is not showing anymore. Now i still get this error: 

  File "/home/sinasta/.config/blender/3.0/scripts/addons/vi-suite061-master/vi_operators.py", line 361, in invoke
    for k in ovp.keys():
RuntimeError: IDPropertyGroup changed size during iteration

location: <unknown location>:-1

I know that this is heavy work in progress and not finnished at all. I will close this issue as soon as you release a stable version. Thanks for your work.
