### ISSUE TITLE
Enabling error: import ft2font

### ISSUE THREAD

**Issue by onceadrog** [rgsouthall/vi-suite061#3]
After importing the addon to 2.93.0, when trying to enable the addon this error occurs:
importError: cannot import name 'ft2font' from partially initialized module 'matplotlib' (most likely due to a circular import) 
Occurs during import of matplotlib in its init.py

**Comment by onceadrog** [comment]
So I've been digging down through the __init__ errors.
There are many instances where filenaming is breaking everything, due to filenames like:
    ft2font.cp37-win_amd64.pyd
instead of:
    ft2font.pyd
    
Then it attempts to bootstrap in kiwisolver (which is originally filenamed kiwisolver.cp37-win_amd64.pyd instead of kiwisolver.pyd), but I can't figure out where it should be to pick it up.

**Comment by onceadrog** [comment]
Also, both ft2font.pyd and kiwisolver.pyd have dependencies for python37.dll
![image](https://user-images.githubusercontent.com/6299372/127908900-e1d9df67-b0b8-40b7-9c14-240c0a8426a3.png)

**Comment by onceadrog** [comment]
And python37.dll conflicts with python 3.9 which is in use by Blender

**Comment by onceadrog** [comment]
New commit solves dependency issues.

File naming still causes enabling addon to fail (e.g. kiwisolver.pyd is still being referred to instead of the actual filename.
Also, it seems to be outside pathing so it cannot find it.

Also, PIL location is not properly referenced during matlabplot setup which causes conflicts with other addons (it tries to import PIL from other addons which are different).

After untangling those issues, I hit a deadend with the following, it looks like there is some pathing or dependency issues, but at his point I'm too entangled to see it:

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\vi-suite061-master\__init__.py", line 98, in <module>
    from .vi_node import vinode_categories, envinode_categories, envimatnode_categories, ViNetwork, No_Loc, So_Vi_Loc
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\vi-suite061-master\vi_node.py", line 37, in <module>
    import matplotlib
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\vi-suite061-master\Python\win32\matplotlib\__init__.py", line 823, in <module>
    cbook._get_data_path("matplotlibrc"),
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\vi-suite061-master\Python\win32\matplotlib\cbook\__init__.py", line 534, in _get_data_path
    return Path(matplotlib.get_data_path(), *args)
AttributeError: module 'matplotlib' has no attribute 'get_data_path'
```
